name: Build

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@master
      name: checkout

    - run: ./.github/build.bat
      name: build

    - uses: actions/upload-artifact@master
      with:
        name: Build
        path: build\LaFlor.7z
      name: upload-build
